package cn.liusiqian.greendaodemo.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "CHAT".
 */
@Entity
public class Chat {

    @Id
    private String msgid;
    private String from;
    private String to;
    private String message;
    private Long timestamp;

    @Generated
    public Chat() {
    }

    public Chat(String msgid) {
        this.msgid = msgid;
    }

    @Generated
    public Chat(String msgid, String from, String to, String message, Long timestamp) {
        this.msgid = msgid;
        this.from = from;
        this.to = to;
        this.message = message;
        this.timestamp = timestamp;
    }

    public String getMsgid() {
        return msgid;
    }

    public void setMsgid(String msgid) {
        this.msgid = msgid;
    }

    public String getFrom() {
        return from;
    }

    public void setFrom(String from) {
        this.from = from;
    }

    public String getTo() {
        return to;
    }

    public void setTo(String to) {
        this.to = to;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public Long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

}
