package cn.liusiqian.greendaodemo.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.liusiqian.greendaodemo.db.User;
import cn.liusiqian.greendaodemo.db.Chat;

import cn.liusiqian.greendaodemo.db.UserDao;
import cn.liusiqian.greendaodemo.db.ChatDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig chatDaoConfig;

    private final UserDao userDao;
    private final ChatDao chatDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        chatDaoConfig = daoConfigMap.get(ChatDao.class).clone();
        chatDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        chatDao = new ChatDao(chatDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Chat.class, chatDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        chatDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public ChatDao getChatDao() {
        return chatDao;
    }

}
