package cn.liusiqian.greendaodemo.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "USER".
 */
@Entity
public class User {

    @Id
    private Long id;
    private Integer work_id;
    private String name;
    private Boolean ismale;
    private String tel;

    @Generated
    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    @Generated
    public User(Long id, Integer work_id, String name, Boolean ismale, String tel) {
        this.id = id;
        this.work_id = work_id;
        this.name = name;
        this.ismale = ismale;
        this.tel = tel;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getWork_id() {
        return work_id;
    }

    public void setWork_id(Integer work_id) {
        this.work_id = work_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean getIsmale() {
        return ismale;
    }

    public void setIsmale(Boolean ismale) {
        this.ismale = ismale;
    }

    public String getTel() {
        return tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

}
